version: '3.1'
volumes:
  trojai_db: null
networks:
  demo:
    name: demo
services:

  postgresql:
    image: postgres
    volumes:
      - trojai_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - demo
    mem_limit: 1G

  trojai-server:
    image: jedp/jedptrojaidemo_api:latest
    environment:
      DB_CONN: "postgresql://user:example@postgresql:5432/trojai"
    ports:
      - "9999:80"
    networks:
      - demo
    depends_on:
      - postgresql
    mem_limit: 1G

  trojai-client:
    image: jedp/trojaidemo_client:latest
    environment:
      API_URL: http://trojai-server
    ports:
      - "80:80"
    networks:
      - demo
    depends_on:
      - postgresql
      - trojai_server
    mem_limit: 1G